"""
Builds the synthetic world SabiID runs against.

No real person's data is used. Names are drawn from common Nigerian given names
and surnames and combined at random. NIN and BVN numbers are random digits with
a deliberately non-real prefix. Dates of birth, states and phone numbers are
random. A seed is fixed so the same run reproduces the same data.

Run:  python -m backend.data_gen        (writes data/sources/*.json, seeds the DB)
"""
from __future__ import annotations

import json
import random

from . import ledger
from .config import DATA_DIR, SOURCES_DIR
from .crypto import bio_hash, issue_sd_credential
from .db import conn, dumps, init_db, now
from .gateway import register_partner
from .simulation import enrolment_bio_sample

SEED = 20260921
GIVEN = ["Adaeze", "Chukwuemeka", "Ngozi", "Oluwaseun", "Ibrahim", "Fatima", "Emeka",
         "Bolanle", "Yusuf", "Chiamaka", "Tunde", "Halima", "Obinna", "Aisha", "Kelechi",
         "Damilola", "Suleiman", "Amarachi", "Segun", "Zainab", "Ikechukwu", "Folake",
         "Nnamdi", "Maryam", "Gbenga", "Uchechi", "Musa", "Temitope", "Chidi", "Rukayat"]
SURNAME = ["Okonkwo", "Adeyemi", "Okafor", "Balogun", "Eze", "Abubakar", "Nwosu",
           "Ajayi", "Bello", "Okeke", "Oladipo", "Ibrahim", "Nwachukwu", "Lawal",
           "Onyeka", "Adewale", "Sani", "Okoro", "Afolabi", "Mohammed", "Chukwu",
           "Ogunleye", "Danladi", "Uche", "Oyelaran"]
STATES = ["Lagos", "Oyo", "Kano", "Rivers", "Enugu", "Kaduna", "FCT Abuja", "Anambra",
          "Plateau", "Borno", "Delta", "Ogun"]

N = 48


def _dob(rng: random.Random, min_year: int, max_year: int) -> str:
    y = rng.randint(min_year, max_year)
    m = rng.randint(1, 12)
    d = rng.randint(1, 28)
    return f"{y:04d}-{m:02d}-{d:02d}"


def generate() -> dict:
    rng = random.Random(SEED)
    citizens = []
    for i in range(N):
        given = rng.choice(GIVEN)
        mid = rng.choice(GIVEN)
        sur = rng.choice(SURNAME)
        full = f"{given} {mid} {sur}"
        # a handful are deliberately minors as of 2026
        if i in (16, 31, 40, 5):
            dob = _dob(rng, 2009, 2015)
        elif i in (11,):
            dob = _dob(rng, 1956, 1962)  # a pensioner
        else:
            dob = _dob(rng, 1968, 2004)
        rec = {
            "index": i,
            "sid": f"SID-NG-{rng.randint(10_000_000, 99_999_999)}",
            "nin": "NIN" + "".join(str(rng.randint(0, 9)) for _ in range(11)),
            "bvn": "BVN" + "".join(str(rng.randint(0, 9)) for _ in range(11)),
            "full_name": full,
            "date_of_birth": dob,
            "state_of_residence": rng.choice(STATES),
            "phone": "+234" + "".join(str(rng.randint(0, 9)) for _ in range(10)),
            "synthetic": True,
            "data_source": "generated by backend/data_gen.py",
        }
        citizens.append(rec)

    # a known, demo-friendly adult in Lagos for the bank scene
    citizens[15]["full_name"] = "Adaeze Chioma Nwosu"
    citizens[15]["date_of_birth"] = "1996-03-14"
    citizens[15]["state_of_residence"] = "Lagos"

    # deliberate source inconsistencies, kept off the payroll roster
    nimc, nibss, civil = {}, {}, {}
    for rec in citizens:
        nimc_name = rec["full_name"]
        nibss_name = rec["full_name"]
        nimc_dob = rec["date_of_birth"]
        nibss_dob = rec["date_of_birth"]

        if rec["index"] == 12:
            # same person, name written in a different order at NIBSS
            g, m, s = rec["full_name"].split()
            nibss_name = f"{m} {g} {s}"
        if rec["index"] == 13:
            # an accent present in one source, dropped in the other
            rec["full_name"] = "Bọlanle Okegbemi Aj-Okegbemi"
            nimc_name = "Bọlanle Okegbemi Aj-Okegbemi"
            nibss_name = "Bolanle Okegbemi Aj-Okegbemi"
        if rec["index"] == 14:
            # a one-year typo in the BVN record
            y, m, d = rec["date_of_birth"].split("-")
            nibss_dob = f"{int(y) + 1:04d}-{m}-{d}"
        if rec["index"] == 20:
            # this person never completed BVN enrolment: NIN only
            pass  # handled below by skipping nibss

        nimc[rec["nin"]] = {"full_name": nimc_name, "date_of_birth": nimc_dob,
                            "state_of_residence": rec["state_of_residence"],
                            "photo_ref": "nimc-photo-" + rec["nin"][-6:]}
        if rec["index"] != 20:
            nibss[rec["bvn"]] = {"full_name": nibss_name, "date_of_birth": nibss_dob,
                                 "phone_hash": bio_hash(rec["phone"])["hash"]}

    # the deceased payroll line: index 10, recorded at the Civil Registration service
    civil[citizens[10]["nin"]] = {"status": "deceased", "death_date": "2025-11-02",
                                  "source": "Civil Registration service (synthetic)"}

    SOURCES_DIR.mkdir(parents=True, exist_ok=True)
    (SOURCES_DIR / "nimc.json").write_text(json.dumps(nimc, indent=2, ensure_ascii=False))
    (SOURCES_DIR / "nibss.json").write_text(json.dumps(nibss, indent=2, ensure_ascii=False))
    (SOURCES_DIR / "civil_registry.json").write_text(json.dumps(civil, indent=2, ensure_ascii=False))
    (DATA_DIR / "synthetic_citizens.json").write_text(
        json.dumps(citizens, indent=2, ensure_ascii=False))
    return {"citizens": citizens, "nimc": nimc, "nibss": nibss, "civil": civil}


def seed_db() -> None:
    init_db()
    c = conn()
    for t in ("citizens", "partners", "revocations", "requests", "ledger",
              "payroll_roster", "payroll_cycles", "payroll_decisions"):
        c.execute(f"DELETE FROM {t}")
    c.execute("DELETE FROM sqlite_sequence WHERE name='ledger'")
    c.commit()

    world = generate()
    citizens = world["citizens"]

    for rec in citizens:
        claims = {
            "full_name": rec["full_name"],
            "date_of_birth": rec["date_of_birth"],
            "state_of_residence": rec["state_of_residence"],
        }
        cred = issue_sd_credential(rec["sid"], claims)
        bio = bio_hash(enrolment_bio_sample(rec["sid"]))
        c.execute(
            "INSERT INTO citizens (sid, nin, bvn, credential, disclosures, bio_enrolment, enrolled_at) "
            "VALUES (?,?,?,?,?,?,?)",
            (rec["sid"], rec["nin"], rec["bvn"], cred["credential"],
             dumps(cred["disclosures"]), dumps(bio), now()),
        )

    register_partner("bank-firsttrust", "First Trust Bank", "bank",
                     ["identity", "age", "name", "state", "kyc_consistency"])
    register_partner("hosp-lasg", "Lagos State General Hospital", "hospital",
                     ["identity", "name", "health"])
    register_partner("payroll-fmw", "Federal Ministry of Works, Payroll Unit", "payroll",
                     ["identity", "liveness", "kyc_consistency"])

    # payroll roster: 7 real active, then relocated, bad_network, deceased,
    # impersonation, and one fabricated line with no identity at all
    plan = [
        (0, "active", 171000), (1, "active", 214500), (2, "active", 98000),
        (3, "active", 305000), (4, "active", 142000), (6, "active", 260000),
        (7, "active", 189000),
        (8, "relocated", 156000), (9, "bad_network", 148000),
        (10, "deceased", 233000), (11, "impersonation", 178000),
    ]
    for idx, gt, amount in plan:
        rec = citizens[idx]
        c.execute(
            "INSERT INTO payroll_roster (employee_no, ministry_id, sid, display_name, "
            "monthly_naira, ground_truth, missed_cycles, last_status) VALUES (?,?,?,?,?,?,0,NULL)",
            (f"FMW-{2200 + idx:04d}", "payroll-fmw", rec["sid"], rec["full_name"], amount, gt),
        )
    c.execute(
        "INSERT INTO payroll_roster (employee_no, ministry_id, sid, display_name, "
        "monthly_naira, ground_truth, missed_cycles, last_status) VALUES (?,?,?,?,?,?,0,NULL)",
        ("FMW-9001", "payroll-fmw", None, "Sunday Adewale Bright", 240000, "fabricated"),
    )

    c.commit()
    ledger.append("system.seeded", actor="operator", subject_sid=None,
                  detail={"citizens": len(citizens), "partners": 3,
                          "payroll_lines": len(plan) + 1, "seed": SEED,
                          "note": "all data is synthetic, generated by data_gen.py"})
    print(f"seeded {len(citizens)} citizens, 3 partners, {len(plan) + 1} payroll lines")


if __name__ == "__main__":
    seed_db()
