"""
Turn the voiceover script plus your recorded voice notes into:

  demo/out/demo.srt          burnt-in-ready subtitles, timed to your audio
  demo/out/assemble.sh       builds demo_final.mp4 = silent video + your VNs + subs

Usage:
  python3 docs/build_srt.py               uses your VNs if present, else target times
  python3 docs/build_srt.py --dry-run     force target times, ignore any VNs

Voice notes go in demo/narration/ named VN01..VN08 with a .m4a, .mp3 or .wav
extension. The script parses docs/VIDEO_SCRIPT.md for the narration text.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPT_MD = ROOT / "docs" / "VIDEO_SCRIPT.md"
NARR_DIR = ROOT / "demo" / "narration"
OUT_DIR = ROOT / "demo" / "out"
SECTIONS_JSON = OUT_DIR / "sections.json"
DRY = "--dry-run" in sys.argv

SECTION_RE = re.compile(
    r"<!--SECTION\s+(\d+)\s*\|\s*(.+?)\s*\|\s*target\s+(\d+)s-->(.*?)<!--/SECTION-->",
    re.DOTALL,
)


def parse_script() -> list[dict]:
    text = SCRIPT_MD.read_text()
    out = []
    for m in SECTION_RE.finditer(text):
        n, title, target, body = m.groups()
        body = body.replace(">>>", " ").replace("\n", " ")
        body = re.sub(r"\s+", " ", body).strip()
        out.append({"n": int(n), "title": title, "target": int(target), "text": body})
    return out


def probe_duration(path: Path) -> float | None:
    try:
        r = subprocess.run(
            ["ffprobe", "-v", "error", "-show_entries", "format=duration",
             "-of", "csv=p=0", str(path)],
            capture_output=True, text=True, check=True,
        )
        return float(r.stdout.strip())
    except Exception:
        return None


def find_vn(n: int) -> Path | None:
    for ext in (".m4a", ".mp3", ".wav", ".aac", ".opus"):
        p = NARR_DIR / f"VN{n:02d}{ext}"
        if p.exists():
            return p
    return None


def split_cues(text: str, max_words: int = 12) -> list[str]:
    parts = re.split(r"(?<=[.?!])\s+", text)
    cues: list[str] = []
    for p in parts:
        words = p.split()
        if len(words) <= max_words:
            cues.append(p.strip())
            continue
        # break a long sentence at commas, then hard-wrap
        chunk: list[str] = []
        for w in words:
            chunk.append(w)
            if len(chunk) >= max_words and w.endswith(","):
                cues.append(" ".join(chunk).strip())
                chunk = []
        if chunk:
            cues.append(" ".join(chunk).strip())
    cues = [c for c in cues if c]
    # fold a tiny trailing fragment back into the line before it
    merged: list[str] = []
    for c in cues:
        if merged and len(c.split()) < 4:
            merged[-1] = merged[-1] + " " + c
        else:
            merged.append(c)
    return merged


def ts(seconds: float) -> str:
    ms = int(round(seconds * 1000))
    h, ms = divmod(ms, 3_600_000)
    m, ms = divmod(ms, 60_000)
    s, ms = divmod(ms, 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def main() -> None:
    sections = parse_script()
    seg_video = {}
    if SECTIONS_JSON.exists():
        for s in json.loads(SECTIONS_JSON.read_text())["sections"]:
            seg_video[s["section"]] = s

    rows, srt, cursor = [], [], 0.0
    cue_no = 0
    for sec in sections:
        vn = None if DRY else find_vn(sec["n"])
        dur = probe_duration(vn) if vn else None
        if dur is None:
            dur = float(sec["target"])
            src = "target"
        else:
            src = vn.name
        vid = seg_video.get(sec["n"], {})
        vid_len = vid.get("seconds", dur)
        rows.append({"section": sec["n"], "title": sec["title"], "audio": src,
                     "audio_s": round(dur, 2), "video_s": round(vid_len, 2),
                     "pad_s": round(dur - vid_len, 2)})

        cues = split_cues(sec["text"])
        weights = [max(len(c), 8) for c in cues]
        total_w = sum(weights)
        t = cursor
        for c, w in zip(cues, weights):
            span = dur * (w / total_w)
            cue_no += 1
            srt.append(f"{cue_no}\n{ts(t)} --> {ts(min(t + span, cursor + dur) - 0.05)}\n{c}\n")
            t += span
        cursor += dur

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "demo.srt").write_text("\n".join(srt))

    # assemble.sh: retime each silent segment to its VN length by trimming or by
    # freezing the last frame, then concatenate, add the joined audio and subs.
    lines = ["#!/usr/bin/env bash",
             "# Generated by docs/build_srt.py. Builds demo/out/demo_final.mp4.",
             "set -euo pipefail",
             'cd "$(dirname "$0")"',
             "rm -rf parts && mkdir parts", ""]
    concat_audio = []
    for r, sec in zip(rows, sections):
        n = r["section"]
        vid = seg_video.get(n)
        vn_glob = f"../narration/VN{n:02d}"
        lines.append(f'VN=$(ls {vn_glob}.* 2>/dev/null | head -1 || true)')
        if vid:
            lines.append(f'ffmpeg -y -ss {vid["start"]} -to {vid["end"]} -i demo.mp4 '
                         f'-an -c:v libx264 -pix_fmt yuv420p parts/seg{n:02d}_raw.mp4')
        else:
            lines.append(f'ffmpeg -y -i demo.mp4 -an -c:v libx264 -pix_fmt yuv420p parts/seg{n:02d}_raw.mp4')
        lines.append('if [ -n "$VN" ]; then')
        lines.append(f'  AD=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$VN")')
        lines.append(f'  ffmpeg -y -i parts/seg{n:02d}_raw.mp4 -vf '
                     f'"tpad=stop_mode=clone:stop_duration=60,trim=duration=${{AD}},setpts=PTS-STARTPTS" '
                     f'-c:v libx264 -pix_fmt yuv420p parts/seg{n:02d}.mp4')
        lines.append(f'  cp "$VN" parts/aud{n:02d}$(echo "$VN" | sed "s/.*\\.//;s/^/./")')
        lines.append("else")
        lines.append(f'  cp parts/seg{n:02d}_raw.mp4 parts/seg{n:02d}.mp4')
        lines.append(f'  ffmpeg -y -f lavfi -i anullsrc=r=44100:cl=stereo -t {r["video_s"]} parts/aud{n:02d}.m4a')
        lines.append("fi")
        lines.append(f'echo "file parts/seg{n:02d}.mp4" >> parts/vlist.txt')
        lines.append(f'ADF=$(ls parts/aud{n:02d}.* | head -1); echo "file $ADF" >> parts/alist.txt')
        lines.append("")
        concat_audio.append(n)
    lines += [
        "ffmpeg -y -f concat -safe 0 -i parts/vlist.txt -c:v libx264 -pix_fmt yuv420p parts/video.mp4",
        "ffmpeg -y -f concat -safe 0 -i parts/alist.txt -c:a aac parts/audio.m4a",
        "ffmpeg -y -i parts/video.mp4 -i parts/audio.m4a -c:v copy -c:a aac -shortest parts/muxed.mp4",
        'ffmpeg -y -i parts/muxed.mp4 -vf "subtitles=demo.srt:force_style=\'FontSize=18,Outline=1,MarginV=60\'" '
        "-c:v libx264 -pix_fmt yuv420p -c:a copy demo_final.mp4",
        'echo "wrote demo/out/demo_final.mp4"',
    ]
    sh = OUT_DIR / "assemble.sh"
    sh.write_text("\n".join(lines) + "\n")
    sh.chmod(0o755)

    print(f"{'sec':>3}  {'audio source':<16} {'audio':>7} {'video':>7} {'pad/trim':>9}  title")
    for r in rows:
        print(f"{r['section']:>3}  {r['audio']:<16} {r['audio_s']:>7} {r['video_s']:>7} "
              f"{r['pad_s']:>9}  {r['title']}")
    total = sum(r["audio_s"] for r in rows)
    print(f"\ntotal narration {total:.1f}s ({total/60:.1f} min)")
    print("wrote demo/out/demo.srt and demo/out/assemble.sh")
    if DRY or not NARR_DIR.exists():
        print("\n(no voice notes found yet: timings above use the script targets. "
              "Record demo/narration/VN01..VN08 then run this again.)")
    else:
        print("\nNext: node demo/build_final.mjs   (server must be running on :8099)")
        print("It re-drives the UI with these captions burned in live, timed to your "
              "voice notes, and writes demo/out/demo_final.mp4. This is the tested path: "
              "assemble.sh needs an ffmpeg built with libass, which this machine's does not "
              "have, so its subtitle-burn step will fail here.")


if __name__ == "__main__":
    main()
